gg_rct_HeroSpawnArea = nil
function InitGlobals()
end

function CreateNeutralHostileBuildings()
local p = Player(PLAYER_NEUTRAL_AGGRESSIVE)
local u
local unitID
local t
local life

u = BlzCreateUnitWithSkin(p, FourCC("h001"), -64.0, 3328.0, 270.000, FourCC("h001"))
u = BlzCreateUnitWithSkin(p, FourCC("h001"), 1984.0, 3008.0, 270.000, FourCC("h001"))
u = BlzCreateUnitWithSkin(p, FourCC("h001"), 3200.0, 192.0, 270.000, FourCC("h001"))
u = BlzCreateUnitWithSkin(p, FourCC("h001"), 2112.0, -2240.0, 270.000, FourCC("h001"))
u = BlzCreateUnitWithSkin(p, FourCC("h001"), -896.0, -2496.0, 270.000, FourCC("h001"))
u = BlzCreateUnitWithSkin(p, FourCC("h001"), -3648.0, 1600.0, 270.000, FourCC("h001"))
u = BlzCreateUnitWithSkin(p, FourCC("h001"), -896.0, 64.0, 270.000, FourCC("h001"))
u = BlzCreateUnitWithSkin(p, FourCC("h001"), 1472.0, 192.0, 270.000, FourCC("h001"))
u = BlzCreateUnitWithSkin(p, FourCC("h001"), -2880.0, -384.0, 270.000, FourCC("h001"))
u = BlzCreateUnitWithSkin(p, FourCC("h001"), -2624.0, -2688.0, 270.000, FourCC("h001"))
u = BlzCreateUnitWithSkin(p, FourCC("h001"), 640.0, -3648.0, 270.000, FourCC("h001"))
u = BlzCreateUnitWithSkin(p, FourCC("h001"), 4800.0, -192.0, 270.000, FourCC("h001"))
u = BlzCreateUnitWithSkin(p, FourCC("h001"), 3584.0, 3200.0, 270.000, FourCC("h001"))
u = BlzCreateUnitWithSkin(p, FourCC("h001"), -1664.0, 2624.0, 270.000, FourCC("h001"))
u = BlzCreateUnitWithSkin(p, FourCC("h001"), 192.0, 1344.0, 270.000, FourCC("h001"))
u = BlzCreateUnitWithSkin(p, FourCC("h001"), 640.0, -1408.0, 270.000, FourCC("h001"))
u = BlzCreateUnitWithSkin(p, FourCC("h001"), 1920.0, 1536.0, 270.000, FourCC("h001"))
u = BlzCreateUnitWithSkin(p, FourCC("h001"), -1856.0, -1280.0, 270.000, FourCC("h001"))
u = BlzCreateUnitWithSkin(p, FourCC("h001"), 3520.0, 1472.0, 270.000, FourCC("h001"))
end

function CreateNeutralPassiveBuildings()
local p = Player(PLAYER_NEUTRAL_PASSIVE)
local u
local unitID
local t
local life

u = BlzCreateUnitWithSkin(p, FourCC("n000"), -6400.0, -7040.0, 270.000, FourCC("n000"))
SetUnitColor(u, ConvertPlayerColor(0))
end

function CreatePlayerBuildings()
end

function CreatePlayerUnits()
end

function CreateAllUnits()
CreateNeutralHostileBuildings()
CreateNeutralPassiveBuildings()
CreatePlayerBuildings()
CreatePlayerUnits()
end

function CreateRegions()
local we

gg_rct_HeroSpawnArea = Rect(-7392.0, -7680.0, -5248.0, -6144.0)
end

function InitCustomPlayerSlots()
SetPlayerStartLocation(Player(0), 0)
ForcePlayerStartLocation(Player(0), 0)
SetPlayerColor(Player(0), ConvertPlayerColor(0))
SetPlayerRacePreference(Player(0), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(0), false)
SetPlayerController(Player(0), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(1), 1)
ForcePlayerStartLocation(Player(1), 1)
SetPlayerColor(Player(1), ConvertPlayerColor(1))
SetPlayerRacePreference(Player(1), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(1), false)
SetPlayerController(Player(1), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(2), 2)
ForcePlayerStartLocation(Player(2), 2)
SetPlayerColor(Player(2), ConvertPlayerColor(2))
SetPlayerRacePreference(Player(2), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(2), false)
SetPlayerController(Player(2), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(3), 3)
ForcePlayerStartLocation(Player(3), 3)
SetPlayerColor(Player(3), ConvertPlayerColor(3))
SetPlayerRacePreference(Player(3), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(3), false)
SetPlayerController(Player(3), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(4), 4)
ForcePlayerStartLocation(Player(4), 4)
SetPlayerColor(Player(4), ConvertPlayerColor(4))
SetPlayerRacePreference(Player(4), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(4), false)
SetPlayerController(Player(4), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(5), 5)
ForcePlayerStartLocation(Player(5), 5)
SetPlayerColor(Player(5), ConvertPlayerColor(5))
SetPlayerRacePreference(Player(5), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(5), false)
SetPlayerController(Player(5), MAP_CONTROL_USER)
SetPlayerStartLocation(Player(6), 6)
SetPlayerColor(Player(6), ConvertPlayerColor(6))
SetPlayerRacePreference(Player(6), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(6), false)
SetPlayerController(Player(6), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(7), 7)
SetPlayerColor(Player(7), ConvertPlayerColor(7))
SetPlayerRacePreference(Player(7), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(7), false)
SetPlayerController(Player(7), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(8), 8)
SetPlayerColor(Player(8), ConvertPlayerColor(8))
SetPlayerRacePreference(Player(8), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(8), false)
SetPlayerController(Player(8), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(9), 9)
SetPlayerColor(Player(9), ConvertPlayerColor(9))
SetPlayerRacePreference(Player(9), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(9), false)
SetPlayerController(Player(9), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(10), 10)
SetPlayerColor(Player(10), ConvertPlayerColor(10))
SetPlayerRacePreference(Player(10), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(10), false)
SetPlayerController(Player(10), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(11), 11)
SetPlayerColor(Player(11), ConvertPlayerColor(11))
SetPlayerRacePreference(Player(11), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(11), false)
SetPlayerController(Player(11), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(12), 12)
SetPlayerColor(Player(12), ConvertPlayerColor(12))
SetPlayerRacePreference(Player(12), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(12), false)
SetPlayerController(Player(12), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(13), 13)
SetPlayerColor(Player(13), ConvertPlayerColor(13))
SetPlayerRacePreference(Player(13), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(13), false)
SetPlayerController(Player(13), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(14), 14)
SetPlayerColor(Player(14), ConvertPlayerColor(14))
SetPlayerRacePreference(Player(14), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(14), false)
SetPlayerController(Player(14), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(15), 15)
SetPlayerColor(Player(15), ConvertPlayerColor(15))
SetPlayerRacePreference(Player(15), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(15), false)
SetPlayerController(Player(15), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(16), 16)
SetPlayerColor(Player(16), ConvertPlayerColor(16))
SetPlayerRacePreference(Player(16), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(16), false)
SetPlayerController(Player(16), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(17), 17)
SetPlayerColor(Player(17), ConvertPlayerColor(17))
SetPlayerRacePreference(Player(17), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(17), false)
SetPlayerController(Player(17), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(18), 18)
SetPlayerColor(Player(18), ConvertPlayerColor(18))
SetPlayerRacePreference(Player(18), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(18), false)
SetPlayerController(Player(18), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(19), 19)
SetPlayerColor(Player(19), ConvertPlayerColor(19))
SetPlayerRacePreference(Player(19), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(19), false)
SetPlayerController(Player(19), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(20), 20)
SetPlayerColor(Player(20), ConvertPlayerColor(20))
SetPlayerRacePreference(Player(20), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(20), false)
SetPlayerController(Player(20), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(21), 21)
SetPlayerColor(Player(21), ConvertPlayerColor(21))
SetPlayerRacePreference(Player(21), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(21), false)
SetPlayerController(Player(21), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(22), 22)
SetPlayerColor(Player(22), ConvertPlayerColor(22))
SetPlayerRacePreference(Player(22), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(22), false)
SetPlayerController(Player(22), MAP_CONTROL_COMPUTER)
SetPlayerStartLocation(Player(23), 23)
SetPlayerColor(Player(23), ConvertPlayerColor(23))
SetPlayerRacePreference(Player(23), RACE_PREF_NIGHTELF)
SetPlayerRaceSelectable(Player(23), false)
SetPlayerController(Player(23), MAP_CONTROL_COMPUTER)
end

function InitCustomTeams()
SetPlayerTeam(Player(0), 0)
SetPlayerTeam(Player(1), 0)
SetPlayerTeam(Player(2), 0)
SetPlayerTeam(Player(3), 0)
SetPlayerTeam(Player(4), 0)
SetPlayerTeam(Player(5), 0)
SetPlayerTeam(Player(6), 0)
SetPlayerTeam(Player(7), 0)
SetPlayerTeam(Player(8), 0)
SetPlayerTeam(Player(9), 0)
SetPlayerTeam(Player(10), 0)
SetPlayerTeam(Player(11), 0)
SetPlayerTeam(Player(12), 0)
SetPlayerTeam(Player(13), 0)
SetPlayerTeam(Player(14), 0)
SetPlayerTeam(Player(15), 0)
SetPlayerTeam(Player(16), 0)
SetPlayerTeam(Player(17), 0)
SetPlayerTeam(Player(18), 0)
SetPlayerTeam(Player(19), 0)
SetPlayerTeam(Player(20), 0)
SetPlayerTeam(Player(21), 0)
SetPlayerTeam(Player(22), 0)
SetPlayerTeam(Player(23), 0)
end

function InitAllyPriorities()
SetStartLocPrioCount(0, 2)
SetStartLocPrio(0, 0, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(0, 1, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(1, 2)
SetStartLocPrio(1, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(1, 1, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(2, 2)
SetStartLocPrio(2, 0, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(2, 1, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(3, 2)
SetStartLocPrio(3, 0, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(3, 1, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(4, 2)
SetStartLocPrio(4, 0, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(4, 1, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(5, 2)
SetStartLocPrio(5, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(5, 1, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(6, 4)
SetStartLocPrio(6, 0, 1, MAP_LOC_PRIO_LOW)
SetStartLocPrio(6, 1, 2, MAP_LOC_PRIO_LOW)
SetStartLocPrio(6, 2, 3, MAP_LOC_PRIO_LOW)
SetStartLocPrio(6, 3, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(6, 8)
SetEnemyStartLocPrio(6, 0, 4, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(6, 1, 7, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(6, 2, 10, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(6, 3, 11, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(6, 4, 15, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(6, 5, 17, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(6, 6, 19, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(7, 20)
SetStartLocPrio(7, 0, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 1, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 2, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 3, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 4, 5, MAP_LOC_PRIO_LOW)
SetStartLocPrio(7, 5, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 6, 8, MAP_LOC_PRIO_LOW)
SetStartLocPrio(7, 7, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(7, 8, 10, MAP_LOC_PRIO_LOW)
SetStartLocPrio(7, 9, 11, MAP_LOC_PRIO_LOW)
SetStartLocPrio(7, 10, 13, MAP_LOC_PRIO_LOW)
SetStartLocPrio(7, 11, 14, MAP_LOC_PRIO_LOW)
SetStartLocPrio(7, 12, 16, MAP_LOC_PRIO_LOW)
SetStartLocPrio(7, 13, 17, MAP_LOC_PRIO_LOW)
SetStartLocPrio(7, 14, 18, MAP_LOC_PRIO_LOW)
SetStartLocPrio(7, 15, 19, MAP_LOC_PRIO_LOW)
SetStartLocPrio(7, 16, 21, MAP_LOC_PRIO_LOW)
SetStartLocPrio(7, 17, 22, MAP_LOC_PRIO_LOW)
SetStartLocPrio(7, 18, 23, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(7, 18)
SetEnemyStartLocPrio(7, 0, 1, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(7, 1, 2, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(7, 2, 3, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(7, 3, 4, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(7, 4, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(7, 5, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(7, 6, 9, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(7, 7, 10, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(7, 8, 11, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(7, 9, 13, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(7, 10, 14, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(7, 11, 16, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(7, 12, 17, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(7, 13, 18, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(7, 14, 19, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(7, 15, 21, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(7, 16, 22, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(7, 17, 23, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(8, 11)
SetStartLocPrio(8, 0, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 1, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 2, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 3, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 4, 11, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 5, 12, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 6, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 7, 15, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 8, 20, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(8, 9, 22, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(8, 21)
SetEnemyStartLocPrio(8, 0, 0, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(8, 1, 1, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(8, 2, 2, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(8, 3, 4, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(8, 4, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(8, 5, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(8, 6, 7, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(8, 7, 9, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(8, 8, 10, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(8, 9, 11, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(8, 10, 12, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(8, 11, 13, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(8, 12, 14, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(8, 13, 16, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(8, 14, 17, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(8, 15, 18, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(8, 16, 19, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(8, 17, 21, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(8, 18, 22, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(8, 19, 23, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(9, 2)
SetStartLocPrio(9, 0, 1, MAP_LOC_PRIO_LOW)
SetStartLocPrio(9, 1, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(9, 16)
SetEnemyStartLocPrio(9, 0, 0, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(9, 1, 1, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(9, 2, 2, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(9, 3, 4, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(9, 4, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(9, 5, 6, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(9, 6, 7, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(9, 7, 8, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(9, 8, 10, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(9, 9, 11, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(9, 10, 12, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(9, 11, 13, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(9, 12, 14, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(9, 13, 20, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(9, 14, 22, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(10, 23)
SetStartLocPrio(10, 0, 0, MAP_LOC_PRIO_LOW)
SetStartLocPrio(10, 1, 1, MAP_LOC_PRIO_LOW)
SetStartLocPrio(10, 2, 2, MAP_LOC_PRIO_LOW)
SetStartLocPrio(10, 3, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 4, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(10, 5, 5, MAP_LOC_PRIO_LOW)
SetStartLocPrio(10, 6, 6, MAP_LOC_PRIO_LOW)
SetStartLocPrio(10, 7, 7, MAP_LOC_PRIO_LOW)
SetStartLocPrio(10, 8, 8, MAP_LOC_PRIO_LOW)
SetStartLocPrio(10, 9, 9, MAP_LOC_PRIO_LOW)
SetStartLocPrio(10, 10, 11, MAP_LOC_PRIO_LOW)
SetStartLocPrio(10, 11, 12, MAP_LOC_PRIO_LOW)
SetStartLocPrio(10, 12, 13, MAP_LOC_PRIO_LOW)
SetStartLocPrio(10, 13, 14, MAP_LOC_PRIO_LOW)
SetStartLocPrio(10, 14, 15, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 15, 16, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 16, 17, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 17, 19, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 18, 20, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 19, 21, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 20, 22, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(10, 21, 23, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(10, 22)
SetEnemyStartLocPrio(10, 0, 0, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(10, 1, 1, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(10, 2, 2, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(10, 3, 3, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(10, 4, 4, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(10, 5, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(10, 6, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(10, 7, 7, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(10, 8, 8, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(10, 9, 9, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(10, 10, 11, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(10, 11, 12, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(10, 12, 13, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(10, 13, 14, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(10, 14, 16, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(10, 15, 17, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(10, 16, 18, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(10, 17, 19, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(10, 18, 21, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(10, 19, 22, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(10, 20, 23, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(11, 6)
SetStartLocPrio(11, 0, 1, MAP_LOC_PRIO_LOW)
SetStartLocPrio(11, 1, 2, MAP_LOC_PRIO_LOW)
SetStartLocPrio(11, 2, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(11, 3, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(11, 4, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(11, 5, 9, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(11, 13)
SetEnemyStartLocPrio(11, 0, 1, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(11, 1, 2, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(11, 2, 3, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(11, 3, 4, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(11, 4, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(11, 5, 9, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(11, 6, 12, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(11, 7, 14, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(11, 8, 15, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(11, 9, 16, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(11, 10, 18, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(11, 11, 22, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(11, 12, 23, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(12, 7)
SetStartLocPrio(12, 0, 11, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(12, 1, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(12, 2, 14, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(12, 3, 16, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(12, 4, 19, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(12, 5, 21, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(12, 6, 22, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(12, 13)
SetEnemyStartLocPrio(12, 0, 0, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(12, 1, 3, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(12, 2, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(12, 3, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(12, 4, 8, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(12, 5, 9, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(12, 6, 10, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(12, 7, 13, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(12, 8, 14, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(12, 9, 16, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(12, 10, 18, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(12, 11, 21, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(12, 12, 22, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(13, 13)
SetStartLocPrio(13, 0, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(13, 1, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(13, 2, 3, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 3, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(13, 4, 6, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 5, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(13, 6, 12, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 7, 14, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 8, 15, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 9, 16, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 10, 18, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 11, 22, MAP_LOC_PRIO_LOW)
SetStartLocPrio(13, 12, 23, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(13, 7)
SetEnemyStartLocPrio(13, 0, 1, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 1, 2, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(13, 2, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 3, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 4, 8, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(13, 5, 10, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(14, 17)
SetStartLocPrio(14, 0, 1, MAP_LOC_PRIO_LOW)
SetStartLocPrio(14, 1, 2, MAP_LOC_PRIO_LOW)
SetStartLocPrio(14, 2, 3, MAP_LOC_PRIO_LOW)
SetStartLocPrio(14, 3, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(14, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(14, 5, 6, MAP_LOC_PRIO_LOW)
SetStartLocPrio(14, 6, 9, MAP_LOC_PRIO_LOW)
SetStartLocPrio(14, 7, 12, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(14, 8, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(14, 9, 16, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(14, 10, 17, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(14, 11, 18, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(14, 12, 19, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(14, 13, 21, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(14, 14, 22, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(14, 15, 23, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(14, 19)
SetEnemyStartLocPrio(14, 0, 1, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(14, 1, 2, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(14, 2, 3, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(14, 3, 4, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(14, 4, 5, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(14, 5, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(14, 6, 7, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(14, 7, 8, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(14, 8, 9, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(14, 9, 12, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(14, 10, 13, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(14, 11, 16, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(14, 12, 17, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(14, 13, 18, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(14, 14, 19, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(14, 15, 21, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(14, 16, 22, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(14, 17, 23, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(15, 19)
SetStartLocPrio(15, 0, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(15, 1, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(15, 2, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(15, 3, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(15, 4, 5, MAP_LOC_PRIO_LOW)
SetStartLocPrio(15, 5, 6, MAP_LOC_PRIO_LOW)
SetStartLocPrio(15, 6, 7, MAP_LOC_PRIO_LOW)
SetStartLocPrio(15, 7, 8, MAP_LOC_PRIO_LOW)
SetStartLocPrio(15, 8, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(15, 9, 12, MAP_LOC_PRIO_LOW)
SetStartLocPrio(15, 10, 13, MAP_LOC_PRIO_LOW)
SetStartLocPrio(15, 11, 14, MAP_LOC_PRIO_LOW)
SetStartLocPrio(15, 12, 16, MAP_LOC_PRIO_LOW)
SetStartLocPrio(15, 13, 17, MAP_LOC_PRIO_LOW)
SetStartLocPrio(15, 14, 18, MAP_LOC_PRIO_LOW)
SetStartLocPrio(15, 15, 19, MAP_LOC_PRIO_LOW)
SetStartLocPrio(15, 16, 21, MAP_LOC_PRIO_LOW)
SetStartLocPrio(15, 17, 22, MAP_LOC_PRIO_LOW)
SetStartLocPrio(15, 18, 23, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(15, 17)
SetEnemyStartLocPrio(15, 0, 1, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(15, 1, 2, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(15, 2, 3, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(15, 3, 4, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 4, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 5, 7, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 6, 9, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 7, 12, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 8, 13, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 9, 14, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 10, 16, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 11, 17, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 12, 18, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 13, 19, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 14, 21, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 15, 22, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(15, 16, 23, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(16, 7)
SetStartLocPrio(16, 0, 1, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 1, 2, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 2, 3, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 3, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 4, 5, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(16, 5, 6, MAP_LOC_PRIO_LOW)
SetStartLocPrio(16, 6, 9, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(16, 2)
SetEnemyStartLocPrio(16, 0, 1, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(16, 1, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(17, 13)
SetStartLocPrio(17, 0, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(17, 1, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(17, 2, 3, MAP_LOC_PRIO_LOW)
SetStartLocPrio(17, 3, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(17, 4, 6, MAP_LOC_PRIO_LOW)
SetStartLocPrio(17, 5, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(17, 6, 12, MAP_LOC_PRIO_LOW)
SetStartLocPrio(17, 7, 14, MAP_LOC_PRIO_LOW)
SetStartLocPrio(17, 8, 15, MAP_LOC_PRIO_LOW)
SetStartLocPrio(17, 9, 16, MAP_LOC_PRIO_LOW)
SetStartLocPrio(17, 10, 18, MAP_LOC_PRIO_LOW)
SetStartLocPrio(17, 11, 22, MAP_LOC_PRIO_LOW)
SetStartLocPrio(17, 12, 23, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(17, 8)
SetEnemyStartLocPrio(17, 0, 0, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(17, 1, 2, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(17, 2, 4, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(17, 3, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(17, 4, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(17, 5, 8, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(17, 6, 10, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(17, 7, 13, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(18, 2)
SetStartLocPrio(18, 0, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(18, 1, 5, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(18, 15)
SetEnemyStartLocPrio(18, 0, 4, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(18, 1, 5, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(18, 2, 7, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(18, 3, 8, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(18, 4, 9, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(18, 5, 12, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(18, 6, 13, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(18, 7, 14, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(18, 8, 16, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(18, 9, 17, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(18, 10, 19, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(18, 11, 21, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(18, 12, 22, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(18, 13, 23, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(19, 14)
SetStartLocPrio(19, 0, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(19, 1, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(19, 2, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(19, 3, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 4, 6, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 5, 7, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 6, 9, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 7, 10, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 8, 13, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 9, 16, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 10, 20, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 11, 21, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 12, 22, MAP_LOC_PRIO_LOW)
SetStartLocPrio(19, 13, 23, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(19, 19)
SetEnemyStartLocPrio(19, 0, 1, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(19, 1, 2, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(19, 2, 3, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(19, 3, 4, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(19, 4, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 5, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 6, 8, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 7, 9, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(19, 8, 10, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 9, 12, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 10, 13, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 11, 14, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 12, 16, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 13, 17, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 14, 18, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 15, 21, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 16, 22, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(19, 17, 23, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(20, 16)
SetStartLocPrio(20, 0, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 1, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 2, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 3, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 4, 8, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 5, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 6, 12, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 7, 13, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 8, 14, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 9, 16, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 10, 17, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 11, 18, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 12, 19, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 13, 21, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 14, 22, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(20, 15, 23, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrioCount(20, 19)
SetEnemyStartLocPrio(20, 0, 1, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(20, 1, 2, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(20, 2, 3, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(20, 3, 4, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(20, 4, 5, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 5, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(20, 6, 7, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 7, 9, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(20, 8, 10, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 9, 12, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 10, 13, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 11, 14, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 12, 16, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 13, 17, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 14, 18, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 15, 19, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 16, 21, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 17, 22, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(20, 18, 23, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(21, 18)
SetStartLocPrio(21, 0, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(21, 1, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(21, 2, 3, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(21, 3, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(21, 4, 5, MAP_LOC_PRIO_LOW)
SetStartLocPrio(21, 5, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(21, 6, 9, MAP_LOC_PRIO_LOW)
SetStartLocPrio(21, 7, 10, MAP_LOC_PRIO_LOW)
SetStartLocPrio(21, 8, 12, MAP_LOC_PRIO_LOW)
SetStartLocPrio(21, 9, 13, MAP_LOC_PRIO_LOW)
SetStartLocPrio(21, 10, 14, MAP_LOC_PRIO_LOW)
SetStartLocPrio(21, 11, 16, MAP_LOC_PRIO_LOW)
SetStartLocPrio(21, 12, 17, MAP_LOC_PRIO_LOW)
SetStartLocPrio(21, 13, 18, MAP_LOC_PRIO_LOW)
SetStartLocPrio(21, 14, 19, MAP_LOC_PRIO_LOW)
SetStartLocPrio(21, 15, 22, MAP_LOC_PRIO_LOW)
SetStartLocPrio(21, 16, 23, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(21, 19)
SetEnemyStartLocPrio(21, 0, 1, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(21, 1, 2, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(21, 2, 3, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(21, 3, 4, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(21, 4, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(21, 5, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(21, 6, 8, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(21, 7, 9, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(21, 8, 10, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(21, 9, 12, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(21, 10, 13, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(21, 11, 14, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(21, 12, 16, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(21, 13, 17, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(21, 14, 18, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(21, 15, 19, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(21, 16, 22, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(21, 17, 23, MAP_LOC_PRIO_LOW)
SetStartLocPrioCount(22, 7)
SetStartLocPrio(22, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(22, 1, 1, MAP_LOC_PRIO_LOW)
SetStartLocPrio(22, 2, 2, MAP_LOC_PRIO_LOW)
SetStartLocPrio(22, 3, 3, MAP_LOC_PRIO_LOW)
SetStartLocPrio(22, 4, 4, MAP_LOC_PRIO_LOW)
SetStartLocPrio(22, 5, 6, MAP_LOC_PRIO_LOW)
SetStartLocPrio(22, 6, 9, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(22, 11)
SetEnemyStartLocPrio(22, 0, 4, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(22, 1, 6, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(22, 2, 7, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(22, 3, 9, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(22, 4, 10, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(22, 5, 13, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(22, 6, 16, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(22, 7, 20, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(22, 8, 21, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(22, 9, 23, MAP_LOC_PRIO_HIGH)
SetStartLocPrioCount(23, 16)
SetStartLocPrio(23, 0, 0, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(23, 1, 1, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(23, 2, 2, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(23, 3, 4, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(23, 4, 5, MAP_LOC_PRIO_LOW)
SetStartLocPrio(23, 5, 6, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(23, 6, 7, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(23, 7, 8, MAP_LOC_PRIO_LOW)
SetStartLocPrio(23, 8, 9, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(23, 9, 10, MAP_LOC_PRIO_LOW)
SetStartLocPrio(23, 10, 11, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(23, 11, 12, MAP_LOC_PRIO_HIGH)
SetStartLocPrio(23, 12, 13, MAP_LOC_PRIO_LOW)
SetStartLocPrio(23, 13, 14, MAP_LOC_PRIO_LOW)
SetStartLocPrio(23, 14, 20, MAP_LOC_PRIO_LOW)
SetStartLocPrio(23, 15, 22, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrioCount(23, 23)
SetEnemyStartLocPrio(23, 0, 0, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(23, 1, 1, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(23, 2, 2, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(23, 3, 3, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(23, 4, 4, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(23, 5, 5, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(23, 6, 6, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(23, 7, 7, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(23, 8, 8, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(23, 9, 9, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(23, 10, 10, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(23, 11, 11, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(23, 12, 12, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(23, 13, 13, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(23, 14, 14, MAP_LOC_PRIO_HIGH)
SetEnemyStartLocPrio(23, 15, 15, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(23, 16, 16, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(23, 17, 17, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(23, 18, 19, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(23, 19, 20, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(23, 20, 21, MAP_LOC_PRIO_LOW)
SetEnemyStartLocPrio(23, 21, 22, MAP_LOC_PRIO_LOW)
end

function main()
SetCameraBounds(-7424.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -7680.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 7424.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 7168.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -7424.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 7168.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 7424.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -7680.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
SetDayNightModels("Environment\\DNC\\DNCAshenvale\\DNCAshenvaleTerrain\\DNCAshenvaleTerrain.mdl", "Environment\\DNC\\DNCAshenvale\\DNCAshenvaleUnit\\DNCAshenvaleUnit.mdl")
SetTerrainFogEx(0, 5000.0, 9000.0, 0.500, 0.000, 0.000, 0.000)
NewSoundEnvironment("Default")
SetAmbientDaySound("AshenvaleDay")
SetAmbientNightSound("AshenvaleNight")
SetMapMusic("Music", true, 0)
CreateRegions()
CreateAllUnits()
InitBlizzard()
InitGlobals()
end

function config()
SetMapName("TRIGSTR_001")
SetMapDescription("TRIGSTR_003")
SetPlayers(24)
SetTeams(24)
SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)
DefineStartLocation(0, 0.0, 4608.0)
DefineStartLocation(1, -4480.0, 1984.0)
DefineStartLocation(2, -3840.0, -2752.0)
DefineStartLocation(3, 1152.0, -4480.0)
DefineStartLocation(4, 4608.0, -1280.0)
DefineStartLocation(5, 4608.0, 3264.0)
DefineStartLocation(6, 6976.0, -7296.0)
DefineStartLocation(7, 6976.0, -7296.0)
DefineStartLocation(8, 6976.0, -7296.0)
DefineStartLocation(9, 6976.0, -7296.0)
DefineStartLocation(10, 6976.0, -7296.0)
DefineStartLocation(11, 6976.0, -7296.0)
DefineStartLocation(12, 6976.0, -7296.0)
DefineStartLocation(13, 6976.0, -7296.0)
DefineStartLocation(14, 6976.0, -7296.0)
DefineStartLocation(15, 6976.0, -7296.0)
DefineStartLocation(16, 6976.0, -7296.0)
DefineStartLocation(17, 6976.0, -7296.0)
DefineStartLocation(18, 6976.0, -7296.0)
DefineStartLocation(19, 6976.0, -7296.0)
DefineStartLocation(20, 6976.0, -7296.0)
DefineStartLocation(21, 6976.0, -7296.0)
DefineStartLocation(22, 6976.0, -7296.0)
DefineStartLocation(23, 6976.0, -7296.0)
InitCustomPlayerSlots()
InitCustomTeams()
InitAllyPriorities()
end

